unstable_features = true

brace_style = "PreferSameLine"
indent_style = "Block"
max_width = 82

imports_layout = "HorizontalVertical"
merge_imports = true

binop_separator = "Back"
empty_item_single_line = true
enum_discrim_align_threshold = 30
inline_attribute_width = 82
overflow_delimited_expr = true
reorder_impl_items = true
struct_field_align_threshold = 30

# fn_call_style = "Block"

fn_args_layout = "Vertical"
fn_params_layout = "Compressed"
fn_single_line = true

wrap_comments = true
# format_code_in_doc_comments = true

use_field_init_shorthand = true
use_try_shorthand = true

# hide_parse_errors=true
